# Why doesn't this work?

- It doesn't run
- It is very specific, i.e., there are hard-coded values
- It doesn't scale
- ...

````
_2020 = pd.read_excel(r'C:\filepath\file.xlsx', 'Stations')

lista_20 = []
listb_20 = []
listc_20 = []


for row in _2020.iterrows():
    if ([_2020['Station Names'] == 'Station_1']):
        lista_20.append(row)
    elif ([_2020['Station Names'] == 'Station_2']):
        listb_20.append(row)
    elif ([_2020['Station Names'] == 'Station_3']):
        listc_20.append(row)
````

In [ ]:
import pandas as pd

In [ ]:
station_delays = pd.DataFrame({"Stations": ["Hamburg", "Hamburg","Hamburg","Hamburg","Bonn", "Berlin","Bonn", "Berlin",
                        "Bonn", "Berlin", "Munich", "Munich"], 
           "delay" : [11, 5, 2, 4, 14, 5, 1, 8, 9, 11, 0, 27 ]})

lista_20 = []
listb_20 = []
listc_20 = []

for row in station_delays.iterrows():
    if ([station_delays['Stations'] == 'Hamburg']):
        lista_20.append(row)
    elif ([station_delays['Stations'] == 'Bonn']):
        listb_20.append(row)
    elif ([station_delays['Stations'] == 'Berlin']):
        listc_20.append(row)

It compiles!

In [ ]:
lista_20

In [ ]:
# Fix the syntax for iterrows

station_delays = pd.DataFrame({"Stations": ["Hamburg", "Hamburg","Hamburg","Hamburg","Bonn", "Berlin","Bonn", "Berlin",
                        "Bonn", "Berlin", "Munich", "Munich"], 
           "delay" : [11, 5, 2, 4, 14, 5, 1, 8, 9, 11, 0, 27 ]})

lista_20 = []
listb_20 = []
listc_20 = []

for index, row in station_delays.iterrows(): # before was not taking into account the return values of iterrows
    if ([station_delays['Stations'] == 'Hamburg']):
        lista_20.append(row)
    elif ([station_delays['Stations'] == 'Bonn']): 
        listb_20.append(row)
    elif ([station_delays['Stations'] == 'Berlin']):
        listc_20.append(row)

In [ ]:
lista_20

This looks better, but not correct.

In [ ]:
listb_20

In [ ]:
listc_20

We never fill lists b or c.

In [ ]:
[station_delays['Stations'] == 'Hamburg']

In [ ]:
if ([station_delays['Stations'] == 'Hamburg']):
    print("True")

In [ ]:
if ([station_delays['Stations'] == 'Bonn']):
    print("True")

In [ ]:
if ([station_delays['Stations'] == 'Berlin']):
    print("True")

Aha!

In [ ]:
station_delays = pd.DataFrame({"Stations": ["Hamburg", "Hamburg","Hamburg","Hamburg","Bonn", "Berlin","Bonn", "Berlin",
                        "Bonn", "Berlin", "Munich", "Munich"], 
           "delay" : [11, 5, 2, 4, 14, 5, 1, 8, 9, 11, 0, 27 ]})

lista_20 = []
listb_20 = []
listc_20 = []

for row in station_delays.iterrows():
    if ([station_delays['Stations'] == 'Hamburg']):
        print(row)

This is not returning rows, but tuples of (index, row)!

In [ ]:
for index, row in station_delays.iterrows():
    if ([station_delays['Stations'] == 'Hamburg']):
        print(row)

By using index, row we are now unpacking the tuples that iterrows() returns.

In [ ]:
for index, row in station_delays.iterrows():
    if (row['Stations'] == 'Hamburg'):
        print(row)

Aha!

In [20]:
# Fix the conditions

station_delays = pd.DataFrame({"Stations": ["Hamburg", "Hamburg","Hamburg","Hamburg","Bonn", "Berlin","Bonn", "Berlin",
                        "Bonn", "Berlin", "Munich", "Munich"], 
           "delay" : [11, 5, 2, 4, 14, 5, 1, 8, 9, 11, 0, 27 ]})

lista_20 = []
listb_20 = []
listc_20 = []

for index, row in station_delays.iterrows():
    if (row['Stations'] == 'Hamburg'):
        lista_20.append(row)
    elif (row['Stations'] == 'Bonn'): 
        listb_20.append(row)
    elif (row['Stations'] == 'Berlin'):
        listc_20.append(row)

In [21]:
lista_20

[Stations    Hamburg
 delay            11
 Name: 0, dtype: object,
 Stations    Hamburg
 delay             5
 Name: 1, dtype: object,
 Stations    Hamburg
 delay             2
 Name: 2, dtype: object,
 Stations    Hamburg
 delay             4
 Name: 3, dtype: object]

In [22]:
listb_20

[Stations    Bonn
 delay         14
 Name: 4, dtype: object,
 Stations    Bonn
 delay          1
 Name: 6, dtype: object,
 Stations    Bonn
 delay          9
 Name: 8, dtype: object]

In [23]:
listc_20

[Stations    Berlin
 delay            5
 Name: 5, dtype: object,
 Stations    Berlin
 delay            8
 Name: 7, dtype: object,
 Stations    Berlin
 delay           11
 Name: 9, dtype: object]

In [18]:
# Now we abstract this (remove hard-coding of variables and "antipatterns")

station_delays = pd.DataFrame({"Stations": ["Hamburg", "Hamburg","Hamburg","Hamburg","Bonn", "Berlin","Bonn", "Berlin",
                        "Bonn", "Berlin", "Munich", "Munich"], 
           "delay" : [11, 5, 2, 4, 14, 5, 1, 8, 9, 11, 0, 27 ]})

for name, group in station_delays.groupby("Stations"):
    print(group)
    print(f"Average delay: {group['delay'].mean()}")

  Stations  delay
5   Berlin      5
7   Berlin      8
9   Berlin     11
Average delay: 8.0
  Stations  delay
4     Bonn     14
6     Bonn      1
8     Bonn      9
Average delay: 8.0
  Stations  delay
0  Hamburg     11
1  Hamburg      5
2  Hamburg      2
3  Hamburg      4
Average delay: 5.5
   Stations  delay
10   Munich      0
11   Munich     27
Average delay: 13.5

In [19]:
station_delays

   Stations  delay
0   Hamburg     11
1   Hamburg      5
2   Hamburg      2
3   Hamburg      4
4      Bonn     14
5    Berlin      5
6      Bonn      1
7    Berlin      8
8      Bonn      9
9    Berlin     11
10   Munich      0
11   Munich     27

In [28]:
for index, row in station_delays.iterrows():
    hamb_delays = 0
    if row["Stations"] == "Hamburg":
        hamb_delays += row["delay"]

print(hamb_delays)

0

In [39]:
hamb_delays = station_delays[station_delays["Stations"] == "Hamburg"]["delay"].sum()

In [41]:
hamb_delay = station_delays[station_delays["Stations"]=="Hamburg"]["delay"].sum()

In [43]:
average_delays=station_delays.groupby("Stations")["delay"].mean()

In [44]:
print(average_delays)

Stations
Berlin      8.0
Bonn        8.0
Hamburg     5.5
Munich     13.5
Name: delay, dtype: float64

In [46]:
station_delays["average_delay"] = station_delays["Stations"].map(average_delays)

In [47]:
station_delays

   Stations  delay  average_delay
0   Hamburg     11            5.5
1   Hamburg      5            5.5
2   Hamburg      2            5.5
3   Hamburg      4            5.5
4      Bonn     14            8.0
5    Berlin      5            8.0
6      Bonn      1            8.0
7    Berlin      8            8.0
8      Bonn      9            8.0
9    Berlin     11            8.0
10   Munich      0           13.5
11   Munich     27           13.5